#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

import os
import sys
import re
import argparse


def run(directory, match, replace, replace_with, prepend, append, display_list, test):
    regex = re.compile(match)
    """ Appends and prepends strings to filenames in a given dir matching a regex. Optionally displays modified files
    and can run without making changes if in test mode  """

    for filename in os.listdir(directory):
        if regex.match(filename):
            new_filename = filename
            new_filename = re.sub(replace, replace_with, filename)
            new_filename = prepend + new_filename + append
            if not test:
                os.rename(directory + filename, directory + new_filename)
            if display_list:
                print filename + (" => " + new_filename if new_filename != filename else "")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A toolkit for editing multiple filenames at once")

    parser.add_argument('-d', '--dir', help='Directory to work on. Defaults to current', default='.')
    parser.add_argument('-m', '--match', help='Process files with given regex', default='.*')
    parser.add_argument('-p', '--prepend', help='Insert string at the beggining of filename', default='')
    parser.add_argument('-a', '--append', help='Insert string at the end of filename', default='')
    parser.add_argument('-l', '--list', help='Show list of processed files', action='store_true')
    parser.add_argument('-t', '--test', help="Changes won't be applied", action='store_true')
    parser.add_argument('-r', '--replace', help="Replace string/regex with other string, defaults repace to ''",
                        nargs='+', default=['']*2)

    args = parser.parse_args(sys.argv[1:])
    if len(args.replace) == 1:
        args.append('')

    run(args.dir, args.match, args.replace[0], args.replace[1], args.prepend, args.append, args.list, args.test)
